# JAWAD HASSAN
# 2230-0035
# BS AI
# ML
# LAB 02

## TASK 1 EDA CHURN DATA SET

In [ ]:
import pandas as pd
df = pd.read_csv("churn.csv")
df=df.transpose()
print('head:',df.head())
print('tail:',df.tail())
df=df.transpose()

head:                      0           1           2           3           4     \
customerID     7590-VHVEG  5575-GNVDE  3668-QPYBK  7795-CFOCW  9237-HQITU   
gender             Female        Male        Male        Male      Female   
SeniorCitizen           0           0           0           0           0   
Partner               Yes          No          No          No          No   
Dependents             No          No          No          No          No   

                     5           6           7           8           9     \
customerID     9305-CDSKC  1452-KIOVK  6713-OKOMC  7892-POOKP  6388-TABGU   
gender             Female        Male      Female      Female        Male   
SeniorCitizen           0           0           0           0           0   
Partner                No          No          No         Yes          No   
Dependents             No         Yes          No          No         Yes   

               ...        7033        7034        7035        7036  

In [32]:
print('shape:', df.shape)
print('columns:', df.columns)
print('total charges sum:',df['TotalCharges'].sum())
print('monthly charges mean:',df['MonthlyCharges'].mean())
print('monthly charges sum:',df['MonthlyCharges'].sum())
df.drop('customerID', axis=1, inplace=True)


shape: (7043, 21)
columns: Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')
total charges sum: 16056168.700000027
monthly charges mean: 64.76169246059922
monthly charges sum: 456116.6000000003


In [35]:
df.isnull().sum()

gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [47]:
print('tenure mean:',df['tenure'].mean())
print('internet service:',df['InternetService'].nunique())
print('total charges 0-10:\n',df.loc[0:10,'TotalCharges'])
print('10 random:\n',df.sample(10))

tenure mean: 32.37114865824223
internet service: 3
total charges 0-10:
 0       29.85
1      1889.5
2      108.15
3     1840.75
4      151.65
5       820.5
6      1949.4
7       301.9
8     3046.05
9     3487.95
10     587.45
Name: TotalCharges, dtype: object
10 random:
       gender SeniorCitizen Partner Dependents tenure PhoneService  \
1036    Male             0     Yes        Yes     68          Yes   
1961  Female             0      No         No     42          Yes   
4984  Female             0      No         No     42          Yes   
4303  Female             0     Yes         No     45          Yes   
3300  Female             0     Yes        Yes     33          Yes   
1310  Female             0     Yes         No     34          Yes   
409     Male             0      No         No      1          Yes   
58    Female             0     Yes        Yes     34          Yes   
284     Male             0     Yes        Yes     18          Yes   
5813    Male             0     Yes    

In [53]:
tenure=df['tenure'].values
print('tenure array:\n',tenure)
print('max:\n',tenure.max())
print('min:\n',tenure.min())
print('mean:\n',tenure.mean().round(6))


tenure array:
 [1 34 2 ... 11 4 66]
max:
 72
min:
 0
mean:
 32.371149


## TASK 2 NUMPY EXERCISE

In [94]:
import numpy as np
array1 = np.random.randint(50 , 100 , size =10)
array2 = np.random.randint(50 , 100 , size =10)

a3=np.sum(array1+array2)
print(a3)
arr1_cross = np.random.randint(50, 100, (2,3))
arr2_cross = np.random.randint(50, 100, (2,3))
a5=np.cross(arr1_cross,arr2_cross)
print(a5)

array1=array1.reshape(2,5)
array2=array2.reshape(5,2)
a4=np.dot(array1,array2)
print(a4)

array1=array1.reshape(2,5)
array2=array2.reshape(2,5)

a6=array1*array2
print(a6)

at=array1.transpose()
print(at)
sum=array1+array2
print(sum)

asub=array1-array2
print(asub)

amult=array1*array2
print(amult)

adiv=array1/array2
print(adiv)

ap=array1**2
print(ap)
asqrt=np.sqrt(array2)
print(asqrt)

ae=np.exp(array1)
print(ae)

al=np.log(array1)
print(al)

print('array1 abs:\n',np.abs(array1))

print('array2 min value:\n',np.min(array2))



1585
[[-1985 -1287  2672]
 [ 1612  -649  -865]]
[[34218 31359]
 [33107 27555]]
[[9603 6984 4896 6612 4080]
 [7055 4800 4740 8096 5248]]
[[99 85]
 [97 50]
 [96 79]
 [76 88]
 [51 82]]
[[196 169 147 163 131]
 [168 146 139 180 146]]
[[  2  25  45 -11 -29]
 [  2 -46  19  -4  18]]
[[9603 6984 4896 6612 4080]
 [7055 4800 4740 8096 5248]]
[[1.02061856 1.34722222 1.88235294 0.87356322 0.6375    ]
 [1.02409639 0.52083333 1.31666667 0.95652174 1.28125   ]]
[[9801 9409 9216 5776 2601]
 [7225 2500 6241 7744 6724]]
[[9.8488578  8.48528137 7.14142843 9.32737905 8.94427191]
 [9.11043358 9.79795897 7.74596669 9.59166305 8.        ]]
[[9.88903032e+42 1.33833472e+42 4.92345829e+41 1.01480039e+33
  1.40934908e+22]
 [8.22301271e+36 5.18470553e+21 2.03828107e+34 1.65163625e+38
  4.09399696e+35]]
[[4.59511985 4.57471098 4.56434819 4.33073334 3.93182563]
 [4.44265126 3.91202301 4.36944785 4.47733681 4.40671925]]
array1 abs:
 [[99 97 96 76 51]
 [85 50 79 88 82]]
array2 min value:
 51
